return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1595934840"]={
    configuration_options={
      base_hp=0.3,
      ghost_button=true,
      ghost_delay=60,
      hunger_kills=true,
      language="auto",
      rip_cmd=true,
      wes_mult=0.5,
      wilson_extra_hp=0.3,
      wilson_speed_mult=0.5 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  } 
}